### ISSUE TITLE
[BUG] Changing PrepGhost option doesn't save

### ISSUE THREAD

**Issue by JustASysAdmin** [Jasonleh99/PlateupPrepGhost#2]
https://youtu.be/DxhU0v1yK58

Changing the option and leaving does not save the new option value.

**Comment by JustASysAdmin** [comment]
I also tested with all other plugins removed and it still happens. 

It seems to be reading the setting correctly, and turning on correctly. Something seems wrong in changing the setting to off.

**Comment by JustASysAdmin** [comment]
Maybe the off value is incorrect? From the BepInEx log

![image](https://user-images.githubusercontent.com/97370685/202860391-eb9dd632-e5ef-4680-b62d-a73f735efa7f.png)

https://github.com/Jasonleh99/PlateupPrepGhost/blob/main/MenuPatch.cs#L55

Is this just always setting to true instead of checking the value?

**Comment by Jasonleh99** [comment]
Oh oops LOL, will fix it when I get home

**Comment by Jasonleh99** [comment]
Fixed with https://github.com/Jasonleh99/PlateupPrepGhost/releases/tag/1.11
