### ISSUE TITLE
Going back to lobby using the Save System mode messes with PrepGhost

### ISSUE THREAD

**Issue by alterNERDtive** [Jasonleh99/PlateupPrepGhost#3]
So https://github.com/Aragami-delp/PlateUp_Mods adds an option to quit back to the lobby. If you do that during the prep phase with ghost on, it will still be on in the lobby and then _not_ be on once you load back into the game. Toggling it off and on fixes it.

I have no idea if you can account for that, but if you can, then please do :)

**Comment by Jasonleh99** [comment]
Hello! fixed with the https://github.com/Jasonleh99/PlateupPrepGhost/releases/tag/1.12 release!
