### ISSUE TITLE
Ghost mode gets stuck on player 2–x

### ISSUE THREAD

**Issue by alterNERDtive** [Jasonleh99/PlateupPrepGhost#4]
If you are playing with other people (at least locally, haven’t tested online) and have PrepGhost enabled, everyone but player 1 will still be in ghost mode once you start the day.

**Comment by Jasonleh99** [comment]
Thanks for catching this, missed it because I was testing solo

Fixed with the https://github.com/Jasonleh99/PlateupPrepGhost/releases/tag/1.12 release !!
