### ISSUE TITLE
Feature Request: Moving Speed

### ISSUE THREAD

**Issue by Firemonkey08** [Jasonleh99/PlateupPrepGhost#5]
Great mod, thanks for this time-saver. Is it possible to increase the moving speed in the preparation phase? Relocate stuff from one end to the other end of the map can take so much time.

**Comment by Jasonleh99** [comment]
Suggestion sounds good to me, I'll probably make a new menu option, however I won't have access to my computer for ~2 weeks so expect this after then :O

**Comment by Jasonleh99** [comment]
Fixed with the newest release https://github.com/Jasonleh99/PlateupPrepGhost/releases/tag/1.20
