### ISSUE TITLE
2 Player issue

### ISSUE THREAD

**Issue by siryampy** [Jasonleh99/PlateupPrepGhost#6]
Downloaded from workshop, works fine other than the fact if player 2 joins they cannot press ESC. Doesn't appear to be an issue their end as I joined as player 2 and also cannot hit ESC. This means that the menu doesn't pop up to do anything like quit, practice mode, etc. 

Player 1 has all functionality though.

**Comment by Jasonleh99** [comment]
Should be fixed by https://github.com/Jasonleh99/PlateupPrepGhost/pull/7
