### ISSUE TITLE
Not working with multiplayer

### ISSUE THREAD

**Issue by ImAnthonyBruh** [Jasonleh99/PlateupPrepGhost#8]
Twice when joining a multiplayer game I could not open the pause menu and was stuck in ghost form. I unsubscribed from the mod and everything worked fine. Great mod, I can't wait to use it more!

**Comment by Aragami-delp** [comment]
Pullrequest that should fix it:
https://github.com/Jasonleh99/PlateupPrepGhost/pull/7

Mod that fixes it for now:
https://steamcommunity.com/sharedfiles/filedetails/?id=2907442859

**Comment by Jasonleh99** [comment]
Should be fixed by https://github.com/Jasonleh99/PlateupPrepGhost/pull/7
